### ISSUE TITLE
Xcode build

### ISSUE THREAD

**Issue by rodrigodzf** [SoundScapeRenderer/SSRemoteVST#14]
Hi, I've ported the JUCE project to Xcode. It built the AU and VST but changed a few things in the source in order to get it to compile under Xcode. Also I'm using JUCE as a submodule with the latest version. The problem is that the finished plugin is not recognized with the linux src and I dont know why (but it works with the src I generated manually), but somehow it looks like it has to do with the introjucer build. Can you add the jucer file so I can try to configure it for xcode?

**Comment by c-bebop** [comment]
We've <b>stopped using</b> the <b>Introjucer</b> for various reasons, this is why there is no Introjucer file.

Could you describe your problem a bit more detailed?

**Comment by rodrigodzf** [comment]
The problem is that compiled plugin doesn't run (it is not correctly recognized or fails to run at all) when it is built straight from the linux src (src folder) using the introjucer for xcode. The way that worked at the end was to use the introjucer template and replace manually each file. The reason for using introjucer is for trying to keep the whole project (and its resources) ready to build for other plattforms or as other plugins. I can try to produce a jucer that builds for linux and mac at least.
